variable vpc_cidr_block {}
variable subnet_cidr_block {}
variable avail_zone {}
variable env_prefix {}
variable my_ip {}
variable instance_type {}
variable image_name {}
variable key_name {}
variable key_file {}
variable user_data_script {}
variable public_key_location {}
variable private_key_location {}